version: '3.4'

services:
  apigateway:
    image: api_gateway
    build:
      context: .
      dockerfile: src/APIGateway/Dockerfile
  msclases:
    image: api_ms_clases
    build:
      context: .
      dockerfile: src/MSClases/Dockerfile
  msprofesores:
    image: api_ms_profesores
    build:
      context: .
      dockerfile: src/MSProfesores/Dockerfile
  appweb:
    image: app_web_blazor
    build:
      context: .
      dockerfile: src/WebApp/Dockerfile
  