apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-db
data:
  initdb.sh: |-
   #!/bin/bash
   set -e
   psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER arley WITH PASSWORD 'qwerty';
    GRANT ALL PRIVILEGES ON DATABASE postgres TO arley;
   EOSQL

   
