// <auto-generated />
using MSClases.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MSClases.Migrations
{
    [DbContext(typeof(DBContextClases))]
    [Migration("20221011195034_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MSClases.Models.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Clase");

                    b.ToTable("Clases", (string)null);
                });

            modelBuilder.Entity("MSClases.Models.ClaseProfesor", b =>
                {
                    b.Property<int>("IdClase")
                        .HasColumnType("int");

                    b.Property<string>("Ci")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("IdClase", "Ci");

                    b.ToTable("ClaseProfesores", (string)null);
                });

            modelBuilder.Entity("MSClases.Models.ClaseProfesor", b =>
                {
                    b.HasOne("MSClases.Models.Clase", "IdClaseNavigation")
                        .WithMany("ClaseProfesor")
                        .HasForeignKey("IdClase")
                        .IsRequired()
                        .HasConstraintName("FK_CLASE");

                    b.Navigation("IdClaseNavigation");
                });

            modelBuilder.Entity("MSClases.Models.Clase", b =>
                {
                    b.Navigation("ClaseProfesor");
                });
#pragma warning restore 612, 618
        }
    }
}
