version: '3'

volumes:
  postgres_demo_data: {}
  ms_user_data: {}

services:
  database-users:
    image: mariadb:latest
    container_name: database-users
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_users
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ms_user_data:/var/lib/mysql
    ports:
      - "3306:3306"

  database-clases-profesores:
    image: postgres:latest
    container_name: database-clases-profesores   
    ports:
      - "5432:5432"
    volumes:
      -  postgres_demo_data:/var/lib/postgresql/data
      - ./create_db_ms-profesores.sql:/docker-entrypoint-initdb.d/create_db_ms-profesores.sql 
    environment:
      POSTGRES_DB: ms_clases
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  ms-clases:
    image: ms-clases:latest
    container_name: ms-clases
    ports:
      - "5056:80"
      - "7014:443"
    restart: always
    depends_on:
      - database-clases-profesores
    environment:
      ConnectionStrings__host: database-clases-profesores
      ConnectionStrings__port: 5432
      ConnectionStrings__database: ms_clases
      ConnectionStrings__user: admin
      ConnectionStrings__password: admin
  
  ms-users:
    image: ms-user:latest
    container_name: ms-users
    ports:
      - "5073:80"
      - "7001:443"
    restart: always
    depends_on:
      - database-users
    environment:
      ConnectionStrings__host: database-users
      ConnectionStrings__port: 3306
      ConnectionStrings__database: ms_users
      ConnectionStrings__user: admin
      ConnectionStrings__password: admin
    
  ms-profesores:
    image: ms-profesores:latest
    container_name: ms-profesores
    ports:
      - "5279:80"
      - "7261:443"
    restart: always
    depends_on:
      - database-clases-profesores
    environment:
      ConnectionStrings__host: database-clases-profesores
      ConnectionStrings__port: 5432
      ConnectionStrings__database: ms_profesores
      ConnectionStrings__user: admin
      ConnectionStrings__password: admin
    
  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "5095:80"
      - "7119:443"
    restart: always
    depends_on:
      - ms-profesores
      - ms-users
      - ms-clases

  app-blazor:
    image: app-blazor:latest
    container_name: app-blazor
    ports:
      - "5050:80"
      - "7142:443"
    restart: always
    depends_on:
      - api-gateway
     
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8081:8080

