version: '3'

volumes:
  ms_clases_data: {}
  ms_user_data: {}

networks:
  ms-net:
    external: false

services:
  database-users:
    image: mariadb:latest
    container_name: database-users
    networks:
      - ms-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_users
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ms_user_data:/var/lib/mysql
    ports:
      - "3306:3306"

  database-clases:
    image: postgres:latest
    container_name: database-clases   
    networks:
      - ms-net
    ports:
      - "5432:5432"
    volumes:
      - ms_clases_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ms_clases
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  ms-clases:
    image: ms-clases:latest
    container_name: ms-clases
    ports:
      - "5056:80"
      - "7014:443"
    networks:
      - ms-net
    restart: always
    depends_on:
      - database-clases
    environment:
      ConnectionStrings__host: database-clases
      ConnectionStrings__port: 5432
      ConnectionStrings__database: ms_clases
      ConnectionStrings__user: admin
      ConnectionStrings__password: admin
  
  ms-users:
    image: ms-user:latest
    container_name: ms-users
    ports:
      - "5073:80"
      - "7001:443"
    networks:
      - ms-net
    restart: always
    depends_on:
      - database-users
    environment:
      ConnectionStrings__host: database-users
      ConnectionStrings__port: 3306
      ConnectionStrings__database: ms_users
      ConnectionStrings__user: admin
      ConnectionStrings__password: admin
  
  pgadmin:
    image: dpage/pgadmin4:4.23
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin     
    ports:
      - "8082:80"
    networks:
      - ms-net
